//! Ephemeris initialization helpers
//!
//! This module provides functionality to extract embedded Swiss Ephemeris files
//! and configure the native Swiss Ephemeris library for use.  
//! It uses `rust-embed` to embed ephemeris files at compile time, and extracts
//! them to a permanent cache folder on disk the first time the library is used.
//!
//! Key points:
//! - Embedded files are stored in `EmbeddedEphemeris` (Rust struct) and must exist
//!   at compile time under `src/swisseph/ephe` (or your folder path).
//! - Extraction only occurs if the target cache folder does not already exist.
//! - The native Swiss Ephemeris library is configured every time by calling
//!   `initialize_ephemeris_with_path()`.
//! - Initialization is thread-safe and idempotent: repeated calls do nothing if extraction has already occurred.
use rust_embed::RustEmbed;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, Once};
use thiserror::Error;

use crate::swerust::handler_swe02::{set_ephe_path, version};
use std::fs;
use std::path::{Path, PathBuf};

/// Type alias for results returned by this module.
pub type Result<T> = std::result::Result<T, EphemerisError>;

/// Errors that may occur during ephemeris extraction or initialization.
#[derive(Debug, Error)]
pub enum EphemerisError {
    #[error("Invalid path: {0:?}")]
    InvalidPath(PathBuf),

    #[error("Path does not exist: {0:?}")]
    PathDoesNotExist(PathBuf),

    #[error("Directory read failed: {0:?}, {1}")]
    DirectoryReadFailed(PathBuf, #[source] std::io::Error),

    #[error("Required files missing in: {0:?}")]
    FilesMissing(PathBuf),

    #[error("Version mismatch, expected: {expected}, found: {found}")]
    VersionMismatch { expected: String, found: String },

    #[error("Failed to create directory {0:?}: {1}")]
    DirectoryCreateFailed(PathBuf, #[source] std::io::Error),

    #[error("Failed to write file {0:?}: {1}")]
    FileWriteFailed(PathBuf, #[source] std::io::Error),

    #[error("Other IO error: {0}")]
    Io(#[from] std::io::Error),
}

/// Represents the embedded ephemeris files.
///
/// This struct is generated by `rust-embed` and contains `.se1`, `.txt`,
/// `.cat`, `.eph` files compiled into the binary at compile time.
/// Use `EmbeddedEphemeris::iter()` to iterate over file names, and
/// `EmbeddedEphemeris::get(file_name)` to get the file data..
#[derive(RustEmbed)]
#[folder = "src/swisseph/ephe"] // your .se1, .txt, .cat, .eph files here
pub struct EmbeddedEphemeris;

// Global synchronization primitives
static INIT_ONCE: Once = Once::new();
static EXTRACTION_COMPLETE: AtomicBool = AtomicBool::new(false);
static EPHEMERIS_PATH: Mutex<Option<PathBuf>> = Mutex::new(None);

/// Ensures that embedded ephemeris files are extracted and the Swiss Ephemeris library is configured.
///
/// - Extracts files from `EmbeddedEphemeris` into a permanent cache directory (if not already present).
/// - Configures the Swiss Ephemeris library to use the extracted files via `initialize_ephemeris_with_path()`.
///
/// # Behavior
/// - Extraction occurs only once per cache folder (i.e., "once forever").
/// - Thread-safe: multiple threads can call this simultaneously without race conditions.
/// - Always sets the library path; safe to call multiple times.
/// - Chooses a permanent location: system cache dir if available, or `target/ephemeris` as fallback.
///
/// # Errors
/// Returns `EphemerisError` if directory creation, file writing, validation, or version check fails.
pub fn ensure_ephemeris_initialized() -> Result<()> {
    // Fast path: if already initialized, just set the path and return
    if EXTRACTION_COMPLETE.load(Ordering::Acquire) {
        let path_guard = EPHEMERIS_PATH.lock().unwrap();
        if let Some(ref path) = *path_guard {
            set_ephemeris_path_only(path)?;
            return Ok(());
        }
    }

    // Slow path: ensure extraction happens exactly once across all threads
    let mut extraction_result = Ok(());

    INIT_ONCE.call_once(|| {
        extraction_result = perform_extraction_and_validation();
    });

    // Check the result of the extraction
    extraction_result?;

    // At this point, extraction is complete. Set the path for this thread.
    let path_guard = EPHEMERIS_PATH.lock().unwrap();
    if let Some(ref path) = *path_guard {
        set_ephemeris_path_only(path)?;
    }

    Ok(())
}

/// Performs the actual file extraction and validation (called only once).
fn perform_extraction_and_validation() -> Result<()> {
    // Choose a permanent, shared cache location
    let target: PathBuf = if let Ok(ephem_dir) = std::env::var("EPHEMERIS_DIR")
    {
        PathBuf::from(ephem_dir)
    } else {
        dirs_next::cache_dir()
            .unwrap_or_else(|| PathBuf::from("target"))
            .join("ephemeris")
    };

    eprintln!("[DEBUG] Using ephemeris directory: {:?}", target);

    // Extract embedded files only if the folder doesn't exist yet
    if !target.exists() {
        eprintln!(
            "[DEBUG] Creating ephemeris directory and extracting files..."
        );

        fs::create_dir_all(&target).map_err(|e| {
            EphemerisError::DirectoryCreateFailed(target.clone(), e)
        })?;

        for file_name in EmbeddedEphemeris::iter() {
            if let Some(file) = EmbeddedEphemeris::get(&file_name) {
                let path = target.join(file_name.as_ref());
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).map_err(|e| {
                        EphemerisError::DirectoryCreateFailed(
                            parent.to_path_buf(),
                            e,
                        )
                    })?;
                }
                fs::write(&path, &file.data).map_err(|e| {
                    EphemerisError::FileWriteFailed(path.clone(), e)
                })?;
                eprintln!("[DEBUG] Extracted file: {:?}", path);
            }
        }
    } else {
        eprintln!(
            "[DEBUG] Ephemeris directory already exists, skipping extraction"
        );
    }

    // Validate the directory contents
    validate_ephemeris_directory(&target)?;

    // Store the path and mark extraction as complete
    {
        let mut path_guard = EPHEMERIS_PATH.lock().unwrap();
        *path_guard = Some(target);
    }

    EXTRACTION_COMPLETE.store(true, Ordering::Release);
    eprintln!(
        "[DEBUG] Ephemeris extraction and validation completed successfully"
    );

    Ok(())
}

/// Validates that the ephemeris directory contains the required files.
fn validate_ephemeris_directory(path: &Path) -> Result<()> {
    if !path.exists() {
        eprintln!("[DEBUG] Ephemeris path does not exist: {:?}", path);
        return Err(EphemerisError::PathDoesNotExist(path.to_path_buf()));
    }

    // Scan the directory for .se1 and .txt files
    let mut has_se1_files = false;
    let mut has_txt_files = false;

    eprintln!("[DEBUG] Validating ephemeris directory: {:?}", path);

    for entry in fs::read_dir(path).map_err(|e| {
        EphemerisError::DirectoryReadFailed(path.to_path_buf(), e)
    })? {
        if let Ok(entry) = entry {
            let p = entry.path();

            if let Some(ext) = p.extension().and_then(|e| e.to_str()) {
                match ext {
                    "se1" => {
                        has_se1_files = true;
                        eprintln!("[DEBUG] Found .se1 file: {:?}", p);
                    },
                    "txt" => {
                        has_txt_files = true;
                        eprintln!("[DEBUG] Found .txt file: {:?}", p);
                    },
                    _ => {},
                }
            }
        }
    }

    if !has_se1_files {
        eprintln!("[DEBUG] No .se1 files found in {:?}", path);
        return Err(EphemerisError::FilesMissing(path.to_path_buf()));
    }
    if !has_txt_files {
        eprintln!("[DEBUG] No .txt files found in {:?}", path);
        return Err(EphemerisError::FilesMissing(path.to_path_buf()));
    }

    eprintln!("[DEBUG] Directory validation successful");
    Ok(())
}

/// Sets the ephemeris path and validates version (called for each thread).
fn set_ephemeris_path_only(path: &Path) -> Result<()> {
    let path_str = path
        .to_str()
        .ok_or_else(|| EphemerisError::InvalidPath(path.to_path_buf()))?;

    eprintln!("[DEBUG] Setting ephemeris path to: {:?}", path_str);
    set_ephe_path(path_str);

    // Validate version
    let found_version = version();
    let expected_version = "2.10.03";
    if found_version != expected_version {
        return Err(EphemerisError::VersionMismatch {
            expected: expected_version.to_string(),
            found: found_version,
        });
    }

    Ok(())
}

/// Initializes Swiss Ephemeris by validating the extracted files and setting the library path.
///
/// This is the original function, kept for backward compatibility but now just validates
/// an existing directory and sets the path.
///
/// # Errors
/// Returns `EphemerisError` if path does not exist, files are missing, or version mismatches.
pub fn initialize_ephemeris_with_path<P: AsRef<Path>>(path: P) -> Result<()> {
    let path = path.as_ref();

    validate_ephemeris_directory(path)?;
    set_ephemeris_path_only(path)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;
    use std::fs::File;
    use std::io::Write;
    use std::path::Path;
    use std::thread;
    use tempfile::tempdir;

    /// Helper: write an arbitrary dummy file inside `dir` with `name`.
    fn write_dummy(dir: &Path, name: &str) -> std::io::Result<()> {
        let p = dir.join(name);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let mut f = File::create(&p)?;
        f.write_all(b"dummy")?;
        Ok(())
    }

    #[test]
    fn initialize_ephemeris_with_valid_se1_and_txt() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path();

        // create dummy se1 and txt files
        write_dummy(dir, "dummy.se1").unwrap();
        write_dummy(dir, "somefile.txt").unwrap();

        let res = initialize_ephemeris_with_path(dir);
        assert!(res.is_ok(), "expected OK for directory with .se1 and .txt");
    }

    #[test]
    fn initialize_ephemeris_missing_se1_returns_error() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path();

        // only txt present
        write_dummy(dir, "only.txt").unwrap();

        let res = initialize_ephemeris_with_path(dir);
        assert!(matches!(res, Err(EphemerisError::FilesMissing(_))));
    }

    #[test]
    fn initialize_ephemeris_missing_txt_returns_error() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path();

        // only se1 present
        write_dummy(dir, "only.se1").unwrap();

        let res = initialize_ephemeris_with_path(dir);
        assert!(matches!(res, Err(EphemerisError::FilesMissing(_))));
    }

    #[test]
    fn test_concurrent_initialization() {
        // This test simulates multiple threads calling ensure_ephemeris_initialized
        // simultaneously to verify thread safety
        let tmp = tempdir().unwrap();
        let extract_dir = tmp.path().to_path_buf();
        env::set_var("EPHEMERIS_DIR", &extract_dir);

        // Pre-create the required files
        write_dummy(&extract_dir, "dummy.se1").unwrap();
        write_dummy(&extract_dir, "dummy.txt").unwrap();

        let handles: Vec<_> = (0..10)
            .map(|i| {
                thread::spawn(move || {
                    println!("Thread {} starting initialization", i);
                    let result = ensure_ephemeris_initialized();
                    println!(
                        "Thread {} finished with result: {:?}",
                        i,
                        result.is_ok()
                    );
                    result
                })
            })
            .collect();

        // Wait for all threads and check results
        for (i, handle) in handles.into_iter().enumerate() {
            let result = handle.join().unwrap();
            assert!(result.is_ok(), "Thread {} failed: {:?}", i, result);
        }
    }
}
